### ISSUE TITLE
Possible C++/Arduino port?

### ISSUE THREAD

**Issue by oyvindkinsey** [nayaverdier/halohome#4]
With the chances of controlling the lights via BT in Home Assistant looking bleak - what do you think about porting the basic logic to c++ so it can be run on a simple ESP32 or similar, exposing the entities via MQTT?

**Comment by aeonSolutions** [comment]
You will find an Arduino Studio (c++) port of the Eaton Halo Home Lights here:
[https://github.com/aeonSolutions/AeonLabs-OpenSourceCode-EatonHaloHome](https://github.com/aeonSolutions/AeonLabs-OpenSourceCode-EatonHaloHome)

**Comment by oyvindkinsey** [comment]
That's unfortunately just using the bridge via the API, and I'm looking for a fully self hosted solution.

**Comment by aeonSolutions** [comment]
OK. I can code that for you. Send me a message on WhatsApp +32 471 632 520 .
